name: SonarQube

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  sonarqube:
    name: Analyse SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.3'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter test --coverage
      - name: SonarQube Scan
        if: env.SONAR_TOKEN != ''
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
